//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 销售_登录记录表
{
    public int ID { get; set; }
    public string 用户 { get; set; }
    public string 用户编号 { get; set; }
    public Nullable<System.DateTime> 登录时间 { get; set; }
    public string 登录地址 { get; set; }
    public Nullable<bool> 是否成功 { get; set; }
    public Nullable<int> 店铺ID { get; set; }
}
