//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 商品档案_SKU_主要参数
{
    public int ID { get; set; }
    public int SKU_ID { get; set; }
    public string 参数名 { get; set; }
    public string 参数值 { get; set; }
    public string 可选项 { get; set; }

    public virtual 商品档案_SKU 商品档案_SKU { get; set; }
}
