//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicStoreManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品档案_型号
    {
        public 商品档案_型号()
        {
            this.商品档案_商品 = new HashSet<商品档案_商品>();
        }
    
        public int ID { get; set; }
        public int 分类ID { get; set; }
        public Nullable<int> 品牌ID { get; set; }
        public Nullable<int> 系列ID { get; set; }
        public string 型号 { get; set; }
        public Nullable<int> 制单人 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public Nullable<bool> 停用标志 { get; set; }
    
        public virtual ICollection<商品档案_商品> 商品档案_商品 { get; set; }
        public virtual 商品档案_分类 商品档案_分类 { get; set; }
    }
}
