//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 销售_设计案提交表_项目相关图纸
{
    public int id { get; set; }
    public int 设计案提交表ID { get; set; }
    public string CAD { get; set; }
    public string 效果3D图 { get; set; }
    public string 比较产品图 { get; set; }
    public string 其它 { get; set; }
    public string 项目提交时间 { get; set; }
    public string 提交备注 { get; set; }
    public string 项目量房时间 { get; set; }
    public string 量房备注 { get; set; }
    public string 项目完成时间 { get; set; }
    public string 备注 { get; set; }

    public virtual 销售_设计案提交表 销售_设计案提交表 { get; set; }
}
