//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicStoreManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 销售_设计案提交表_客户意向产品明细
    {
        public int id { get; set; }
        public string 接待序号 { get; set; }
        public int 设计提交案 { get; set; }
        public string 空间 { get; set; }
        public string 系列 { get; set; }
        public string 产品名称 { get; set; }
        public byte[] 图片 { get; set; }
        public string 尺寸 { get; set; }
        public string 单位 { get; set; }
        public Nullable<int> 数量 { get; set; }
        public string 配置 { get; set; }
    
        public virtual 销售_设计案提交表 销售_设计案提交表 { get; set; }
    }
}
