//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 商品档案_SPU_主要参数_可选项
{
    public int ID { get; set; }
    public int 参数ID { get; set; }
    public string 可选项 { get; set; }
    public Nullable<int> 制单人 { get; set; }
    public Nullable<System.DateTime> 制单日期 { get; set; }

    public virtual 商品档案_SPU_主要参数 商品档案_SPU_主要参数 { get; set; }
    public virtual 商品档案_SPU_主要参数_可选项 商品档案_SPU_主要参数_可选项1 { get; set; }
    public virtual 商品档案_SPU_主要参数_可选项 商品档案_SPU_主要参数_可选项2 { get; set; }
}
