//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChicStoreManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品档案_SPU
    {
        public 商品档案_SPU()
        {
            this.商品档案_SKU = new HashSet<商品档案_SKU>();
        }
    
        public int ID { get; set; }
        public string 编号 { get; set; }
        public string 名称1 { get; set; }
        public string 规格1 { get; set; }
        public string SPU描述 { get; set; }
        public string 计量单位1 { get; set; }
        public Nullable<int> 商品ID { get; set; }
        public Nullable<int> 型号ID { get; set; }
        public Nullable<bool> 停用标志 { get; set; }
        public Nullable<int> 交货周期1 { get; set; }
        public Nullable<bool> 是否进口1 { get; set; }
        public Nullable<int> 制单人 { get; set; }
        public Nullable<System.DateTime> 制单日期 { get; set; }
        public Nullable<decimal> 零售价 { get; set; }
        public Nullable<decimal> 经销价 { get; set; }
        public Nullable<bool> 审核标志 { get; set; }
        public Nullable<int> 审核人 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public Nullable<bool> 处理标识 { get; set; }
    
        public virtual ICollection<商品档案_SKU> 商品档案_SKU { get; set; }
        public virtual 商品档案_商品 商品档案_商品 { get; set; }
    }
}
