//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class 商品档案_品牌
{
    public 商品档案_品牌()
    {
        this.销售_店铺档案 = new HashSet<销售_店铺档案>();
    }

    public int ID { get; set; }
    public string 品牌名称 { get; set; }
    public string 品牌介绍 { get; set; }
    public string 品牌LOGO { get; set; }
    public Nullable<int> 制单人 { get; set; }
    public Nullable<System.DateTime> 制单日期 { get; set; }

    public virtual ICollection<销售_店铺档案> 销售_店铺档案 { get; set; }
}
